Make "import" feature work again
Before this commit, the "import" feature was broken and printed the
following error message:

    Error: <WordPair: ...> instance isn't saved. Use bulk=False or save
    the object first.

The reason is Django requires bulk=False since 1.10. Commit
f4954842a8d87c4d250c40fa567d7bf65147b155 fixed this at one place. This
commit fixes another place.

The description of the change from the Django documentation:

- RelatedManager.add: "The bulk parameter was added. In older versions,
  foreign key updates were always done using save(). Use bulk=False if
  you require the old behavior."
  https://docs.djangoproject.com/en/1.10/ref/models/relations/#django.db.models.fields.related.RelatedManager.add
  p